language: c

os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="0.12"
    - export NODE_VERSION="0.10"

matrix:
  fast_finish: true

before_install:
  - echo $TRAVIS_OS_NAME
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
  - npm install -g gulp
  - 'npm install -g git://github.com/tars/tars-cli.git#${TRAVIS_COMMIT}'

script:
  - tars --version
  - mkdir tars-temp
  - cd tars-temp
  - tars init -s https://github.com/tars/tars/archive/version-1.3.0.zip
  - tars re-init
  - tars add-module new
  - tars add-page main.html
  - tars add-page inner
  - tars build --release --ie8
