language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp
  - npm install -g tars-cli
script:
  - tars --version
  - mkdir tars-temp
  - cd tars-temp
  - tars init -s https://github.com/tars/tars/archive/version-1.3.0-cli-integration.zip
  - tars add-module new
  - tars add-page main.html
  - tars add-page inner
  - tars build --release --ie8
