language: c

os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="0.12"
    - export NODE_VERSION="4"

matrix:
  fast_finish: true

before_install:
  - echo $TRAVIS_OS_NAME
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
  - 'npm install -g git://github.com/tars/tars-cli.git#${TRAVIS_COMMIT}'

script:
  - tars --version
  - mkdir tars-temp
  - cd tars-temp
  - tars init --silent
  - tars re-init --silent
  - tars add-module new -e
  - tars add-module new1 -f
  - tars add-module new2 -b
  - tars add-module new3 -a
  - tars add-module new4 -i
  - tars add-module new5 -d
  - tars add-page main.html
  - tars add-page inner
  - tars add-page contacts -e
  - tars build --release --ie8
