# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 5

install:
  - cmd: npm -v
  - cmd: node -v
  - cmd: 'npm install -g git://github.com/tars/tars-cli.git#%APPVEYOR_REPO_COMMIT%'

build: off

test_script:
  - cmd: tars --version
  - cmd: mkdir tars-temp
  - cmd: cd tars-temp
  - cmd: tars init --silent --source https://github.com/tars/tars/archive/version-1.5.0.zip
  - cmd: tars re-init --silent
  - cmd: tars start re-init --flags '--silent'
  - cmd: tars add-module new -e
  - cmd: tars add-module new1 -f
  - cmd: tars add-module new2 -b
  - cmd: tars add-module new3 -a
  - cmd: tars add-module new4 -i
  - cmd: tars add-module new5 -d
  - cmd: tars add-page main.html
  - cmd: tars add-page inner
  - cmd: tars add-page contacts -e
  - cmd: tars build --release --ie


